### ISSUE TITLE
What is $fit?

### ISSUE THREAD

**Issue by markseeto** [gbm-developers/gbm#41]
What is the `fit` element of a gbm object?

The documentation says that it's "a vector containing the fitted values on the scale of regression function (e.g. log-odds scale for bernoulli, log scale for poisson)". That seems clear enough, but I would have expected it to be the same as the predictions from predict() applied to the training data, but it's not.

Example:

```
library(gbm)

set.seed(1)

gbm.iris <- gbm(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
                data = iris, distribution = "multinomial",
                bag.fraction = 1, n.trees = 3)

# What is gbm.iris$fit ?
# Why isn't it the same as predict(gbm.iris, n.trees = 3)[, , 1] ?

predict(gbm.iris, n.trees = 3)[, , 1] - gbm.iris$fit  # many entries are 0 but not all

# First 10 rows:

##         setosa versicolor  virginica
##  [1,]  0.00000  0.0000000  0.0000000
##  [2,]  1.15344 -0.4248330  0.0000000
##  [3,]  1.15344 -0.2223908 -1.0816416
##  [4,]  0.00000  0.0000000  0.0000000
##  [5,]  0.00000  0.0000000  0.0000000
##  [6,]  0.00000  0.0000000  0.0000000
##  [7,]  0.00000  0.0000000  0.0000000
##  [8,]  0.00000  0.0000000  0.0000000
##  [9,]  0.00000  0.0000000  0.0000000
## [10,]  0.00000  0.0000000  0.0000000
```

I'm using gbm version 2.1.5.

Thanks.

**Comment by gregridgeway** [comment]
I would recommend switching to gbm3 posted on github. And I would not recommend using gbm's multinomial option...I don't think it was ever debugged and had a number of issues. We've actually removed it from gbm3.
-------- Original message --------From: markseeto <notifications@github.com> Date: 6/28/19  8:52 PM  (GMT-05:00) To: gbm-developers/gbm <gbm@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [gbm-developers/gbm] What is $fit? (#41) I asked this question on Stackoverflow but it hasn't been answered: https://stackoverflow.com/questions/56606815/gbm-in-r-what-is-fit
What is the fit element of a gbm object?
The documentation says that it's "a vector containing the fitted values on the scale of regression function (e.g. log-odds scale for bernoulli, log scale for poisson)". That seems clear enough, but I would have expected it to be the same as the predictions from predict() applied to the training data, but it's not.
Example:
library(gbm)

set.seed(1)

gbm.iris <- gbm(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
                data = iris, distribution = "multinomial",
                bag.fraction = 1, n.trees = 3)

# What is gbm.iris$fit ?
# Why isn't it the same as predict(gbm.iris, n.trees = 3)[, , 1] ?

predict(gbm.iris, n.trees = 3)[, , 1] - gbm.iris$fit  # many entries are 0 but not all

# First 10 rows:

##         setosa versicolor  virginica
##  [1,]  0.00000  0.0000000  0.0000000
##  [2,]  1.15344 -0.4248330  0.0000000
##  [3,]  1.15344 -0.2223908 -1.0816416
##  [4,]  0.00000  0.0000000  0.0000000
##  [5,]  0.00000  0.0000000  0.0000000
##  [6,]  0.00000  0.0000000  0.0000000
##  [7,]  0.00000  0.0000000  0.0000000
##  [8,]  0.00000  0.0000000  0.0000000
##  [9,]  0.00000  0.0000000  0.0000000
## [10,]  0.00000  0.0000000  0.0000000

I'm using gbm version 2.1.5.
Thanks.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gbm-developers/gbm/issues/41?email_source=notifications\u0026email_token=ACERTQFW6EV43BUYUKDKXELP42W5JA5CNFSM4H4JIQJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G4NLTCA",
"url": "https://github.com/gbm-developers/gbm/issues/41?email_source=notifications\u0026email_token=ACERTQFW6EV43BUYUKDKXELP42W5JA5CNFSM4H4JIQJKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G4NLTCA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by markseeto** [comment]
Thanks for your reply Greg, and thanks for your work on these packages.
